# Generated by Django 5.2.7 on 2025-11-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Variation_item',
            new_name='variation_item',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='Variation_value',
            new_name='variation_value',
        ),
        migrations.AlterField(
            model_name='variation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
