# Generated by Django 6.0 on 2026-01-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
