# Generated by Django 6.0 on 2026-01-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_alter_category_options_category_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/category'),
        ),
        migrations.AlterField(
            model_name='category_item',
            name='image',
            field=models.ImageField(upload_to='media/Item'),
        ),
    ]
