# Generated by Django 6.0 on 2026-01-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0004_category_category_photo_alter_category_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_item',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
    ]
