# Generated by Django 6.0 on 2026-01-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0005_category_item_is_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_item',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='category_item',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
