# Generated by Django 6.0 on 2026-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_category_item_is_available_category_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_item',
            name='price',
            field=models.IntegerField(max_length=50),
        ),
    ]
