# Generated by Django 6.0 on 2026-01-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_alter_category_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_item',
            name='item_slug',
            field=models.SlugField(blank=True),
        ),
    ]
